### ISSUE TITLE
Status Bar to short-cuts menu bar ?

### ISSUE THREAD

**Issue by SheepDomination** [JerryGoyal/Shortcut-Menu-Bar-VSCode-Extension#2]
Adding the contents of the status bar to the short-cuts menu bar, if; like me, the user has the status bar hidden in the settings ?
It may seem as a contradiction but the status bar takes up screen estate, the short-cuts menu bar is visible as long as the tabs are visible, no extra screen estate occupied.

**Comment by JerryGoyal** [comment]
Are you referring to the status bar which is in bottom? if yes, there are many buttons and showing all those buttons in the tabs menu will occupy much of space and hence, less file tabs will be visible. I wanted to add only the most useful commands to the tab menu so that it doesn't cover much of space in tabs menu.
What I can do is to let users add their own commands to the shortcut menu bar. But, this seems a little tricky to achieve, I'll find a way if it's possible.

**Comment by rei-vilo** [comment]
> What I can do is to let users add their own commands to the shortcut menu bar. But, this seems a little tricky to achieve, I'll find a way if it's possible.

That would be really great!

**Comment by SheepDomination** [comment]
Any update ?

**Comment by SheepDomination** [comment]
@JerryGoyal Thanks, I look forward to it ;)

**Comment by JerryGoyal** [comment]
I updated the extension now user can enable/disable the buttons they want from extension settings. However users still cant create new buttons so they need to request to create it. I created 2 to toggle activity bar & terminal.

**Comment by JerryGoyal** [comment]
also note that menu bar can only have buttons and can not show any kind of status like status bar (afaik)

**Comment by SheepDomination** [comment]
Is it possible to have the icons in the activity bar within the activity bar ? 
The status bar in the activity bar would be a good option.

**Comment by JerryGoyal** [comment]
status bar is quite below for handy icons and it usually contain information about the file opened. Adding custom commands to status bar/activity bar is possible but it would be overkill in my opinion.
